name = "PDMPFlux"
uuid = "fa921718-cbf9-4165-aaee-7047d51b02b3"
version = "0.4.3"
authors = ["Hirofumi Shiba"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PolyesterForwardDiff = "98d1487c-24ca-40b6-b7ab-df2af84e126b"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
BenchmarkTools = "1.6.0"
Distributions = "0.25.112"
ForwardDiff = "0.10.36, 1"
LaTeXStrings = "1.4.0"
LinearAlgebra = "1.11.0"
Optim = "1.9.4"
Plots = "1.40.8"
PolyesterForwardDiff = "0.1.2"
ProgressBars = "1.5.1"
Random = "1.11.0"
ReverseDiff = "1.15.3"
StaticArrays = "1"
Statistics = "1.11.1"
StatsPlots = "0.15.7"
Test = "1.11.0"
Zygote = "0.6.72, 0.7"
julia = "1.11.1"
